{{- if and .Values.proxy.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.proxy.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  {{- if not .Values.proxy.autoscaling.enabled }}
  replicas: {{ .Values.proxy.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: proxy
      annotations:
        checksum/proxy-config: {{ include (print $.Template.BasePath "/proxy/configmap.yaml") . | sha256sum }}
      {{- if .Values.proxy.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.proxy.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "dify.proxy.serviceAccountName" . }}
      {{- if .Values.proxy.podSecurityContext }}
      securityContext:
        {{- include "common.tplvalues.render" (dict "value" .Values.proxy.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.image.proxy.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.proxy.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: nginx
          image: {{ include "common.images.image" (dict "imageRoot" .Values.image.proxy "global" .Values.global) }}
          imagePullPolicy: {{ .Values.image.proxy.pullPolicy }}
          {{- if .Values.proxy.containerSecurityContext }}
          securityContext:
            {{- include "common.tplvalues.render" (dict "value" .Values.proxy.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.proxy.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.proxy.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.proxy.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.proxy.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.proxy.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.proxy.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          env:
        {{- if .Values.proxy.extraEnv }}
          {{- toYaml .Values.proxy.extraEnv | nindent 8 }}
        {{- end }}
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
          resources: {{- toYaml .Values.proxy.resources | nindent 12 }}
          volumeMounts:
            - name: nginx
              mountPath: /etc/nginx/nginx.conf
              readOnly: true
              subPath: nginx.conf
            - name: nginx
              mountPath: /etc/nginx/proxy.conf
              readOnly: true
              subPath: proxy.conf
            - name: nginx
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
              subPath: default.conf
        {{- if .Values.proxy.log.persistence.enabled }}
            - name: nginx-logs-disk
              mountPath: {{ .Values.proxy.log.persistence.mountPath | quote }}
              subPath: {{ .Values.proxy.log.persistence.persistentVolumeClaim.subPath | default "" }}
        {{- end }}
      {{- if .Values.proxy.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.proxy.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.proxy.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.proxy.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.proxy.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.proxy.tolerations "context" $) | nindent 8 }}
      {{- end }}
      volumes:
        - name: nginx
          configMap:
            defaultMode: 420
            name: {{ template "dify.proxy.fullname" . }}
      {{- if .Values.proxy.log.persistence.enabled }}
        - name: nginx-logs-disk
          persistentVolumeClaim:
            claimName: {{ .Values.proxy.log.persistence.persistentVolumeClaim.existingClaim | default (printf "%s-logs" (include "dify.nginx.fullname" . | trunc 58)) }}
      {{- end }}
{{- end }}
