apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dify.api.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  {{- include "dify.api.config" . | nindent 2 }}
