apiVersion: v1
kind: Service
metadata:
  name: {{ include "dify.api.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: api
    {{- if .Values.api.service.labels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.api.service.labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.api.service.annotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" .Values.api.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- if .Values.api.service.clusterIP }}
  clusterIP: {{ .Values.api.service.clusterIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
