apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dify.web.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: web
data:
  {{- include "dify.web.config" . | nindent 2 }}

