apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dify.worker.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: worker
data:
  {{- include "dify.worker.config" . | nindent 2 }}

