apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dify.worker.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: worker
type: Opaque
data:
  {{- include "dify.worker.credentials" . | nindent 2 }}
