apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dify.pluginDaemon.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: plugin-daemon
type: Opaque
data:
  {{- include "dify.pluginDaemon.credentials" . | nindent 2 }}

